/**
 * Documented registry of every legal `--kw-*` custom property, mirroring
 * primitive.css / semantic.css / component.css. This is the single source
 * of truth the token audit (../token-audit.ts) checks references against —
 * add a variable to a CSS layer and to this list together, or the audit
 * will flag it as undeclared.
 */

export type TokenLayer = "primitive" | "semantic" | "component";

export interface TokenDescriptor {
  /** Variable name without the leading `--`. */
  name: string;
  layer: TokenLayer;
  description: string;
}

const primitiveTokens: readonly TokenDescriptor[] = [
  { name: "kw-p-color-bone-50", layer: "primitive", description: "Kept Light lightest neutral (raised panels)." },
  { name: "kw-p-color-bone-100", layer: "primitive", description: "Kept Light base canvas neutral." },
  { name: "kw-p-color-bone-200", layer: "primitive", description: "Kept Light page-background neutral." },
  { name: "kw-p-color-bone-300", layer: "primitive", description: "Kept Light hairline border neutral." },
  { name: "kw-p-color-graphite-600", layer: "primitive", description: "Kept Light faint/placeholder text." },
  { name: "kw-p-color-graphite-700", layer: "primitive", description: "Kept Light secondary text." },
  { name: "kw-p-color-graphite-900", layer: "primitive", description: "Kept Light primary text ink." },
  { name: "kw-p-color-clay-400", layer: "primitive", description: "Kept Light muted accent (accent backgrounds)." },
  { name: "kw-p-color-clay-600", layer: "primitive", description: "Kept Light accent — used sparingly." },
  { name: "kw-p-color-moss-500", layer: "primitive", description: "Kept Light calm/secondary state hue." },
  { name: "kw-p-color-charcoal-950", layer: "primitive", description: "Hy3 deepest near-black canvas." },
  { name: "kw-p-color-charcoal-900", layer: "primitive", description: "Hy3 raised panel." },
  { name: "kw-p-color-charcoal-850", layer: "primitive", description: "Hy3 sunken/recessed panel." },
  { name: "kw-p-color-parchment-100", layer: "primitive", description: "Hy3 primary text." },
  { name: "kw-p-color-parchment-400", layer: "primitive", description: "Hy3 secondary/faint text." },
  { name: "kw-p-color-ember-300", layer: "primitive", description: "Hy3 ember highlight (presence hot spot)." },
  { name: "kw-p-color-ember-400", layer: "primitive", description: "Hy3 accent — used sparingly." },
  { name: "kw-p-color-ember-glow", layer: "primitive", description: "Hy3 ember glow, alpha-blended." },
  { name: "kw-p-color-ember-glow-faint", layer: "primitive", description: "Hy3 faint ambient body-glow tint." },
  { name: "kw-p-color-ember-line", layer: "primitive", description: "Hy3 hairline border, alpha-blended ember." },
  { name: "kw-p-color-line-soft-dark", layer: "primitive", description: "Hy3 soft neutral hairline." },
  { name: "kw-p-color-sage-500", layer: "primitive", description: "Hy3 calm/secondary state hue." },
  { name: "kw-p-color-white", layer: "primitive", description: "Absolute white, structural use only." },
  { name: "kw-p-color-transparent", layer: "primitive", description: "Structural transparency." },
  { name: "kw-p-color-state-calm-light", layer: "primitive", description: "Light-theme calm-state color (pairs with a glyph, never color-alone)." },
  { name: "kw-p-color-state-attention-light", layer: "primitive", description: "Light-theme attention-state color (pairs with a glyph)." },
  { name: "kw-p-color-state-calm-dark", layer: "primitive", description: "Dark-theme calm-state color (pairs with a glyph)." },
  { name: "kw-p-color-state-attention-dark", layer: "primitive", description: "Dark-theme attention-state color (pairs with a glyph)." },
  { name: "kw-p-font-serif-light", layer: "primitive", description: "Kept Light display/body serif stack." },
  { name: "kw-p-font-serif-dark", layer: "primitive", description: "Hy3 display serif stack." },
  { name: "kw-p-font-sans-light", layer: "primitive", description: "Kept Light label sans stack." },
  { name: "kw-p-font-sans-dark", layer: "primitive", description: "Hy3 body sans stack." },
  { name: "kw-p-font-mono-dark", layer: "primitive", description: "Hy3 eyebrow/timestamp mono stack." },
  { name: "kw-p-font-size-050", layer: "primitive", description: "11px — eyebrows, timestamps." },
  { name: "kw-p-font-size-100", layer: "primitive", description: "13px — labels." },
  { name: "kw-p-font-size-200", layer: "primitive", description: "15px." },
  { name: "kw-p-font-size-300", layer: "primitive", description: "16px — body." },
  { name: "kw-p-font-size-400", layer: "primitive", description: "17px." },
  { name: "kw-p-font-size-500", layer: "primitive", description: "20px — subheading." },
  { name: "kw-p-font-size-600", layer: "primitive", description: "24px." },
  { name: "kw-p-font-size-700", layer: "primitive", description: "28px — heading." },
  { name: "kw-p-font-size-800", layer: "primitive", description: "36px." },
  { name: "kw-p-font-size-900", layer: "primitive", description: "44px — display." },
  { name: "kw-p-line-height-tight", layer: "primitive", description: "Tight line-height for headings." },
  { name: "kw-p-line-height-normal", layer: "primitive", description: "Body line-height." },
  { name: "kw-p-line-height-relaxed", layer: "primitive", description: "Relaxed line-height for long-form text." },
  { name: "kw-p-letter-spacing-normal", layer: "primitive", description: "No tracking." },
  { name: "kw-p-letter-spacing-tracked", layer: "primitive", description: "Wide tracking for eyebrows/labels." },
  { name: "kw-p-letter-spacing-tracked-tight", layer: "primitive", description: "Slightly tracked, for small caps." },
  { name: "kw-p-space-050", layer: "primitive", description: "2px." },
  { name: "kw-p-space-100", layer: "primitive", description: "4px." },
  { name: "kw-p-space-150", layer: "primitive", description: "6px." },
  { name: "kw-p-space-200", layer: "primitive", description: "8px." },
  { name: "kw-p-space-300", layer: "primitive", description: "12px." },
  { name: "kw-p-space-400", layer: "primitive", description: "16px." },
  { name: "kw-p-space-500", layer: "primitive", description: "20px." },
  { name: "kw-p-space-600", layer: "primitive", description: "24px." },
  { name: "kw-p-space-800", layer: "primitive", description: "32px." },
  { name: "kw-p-space-1000", layer: "primitive", description: "40px." },
  { name: "kw-p-space-1200", layer: "primitive", description: "48px." },
  { name: "kw-p-space-1600", layer: "primitive", description: "64px." },
  { name: "kw-p-radius-000", layer: "primitive", description: "0 — square corners." },
  { name: "kw-p-radius-xs", layer: "primitive", description: "4px." },
  { name: "kw-p-radius-sm", layer: "primitive", description: "8px." },
  { name: "kw-p-radius-md", layer: "primitive", description: "12px." },
  { name: "kw-p-radius-lg", layer: "primitive", description: "16px." },
  { name: "kw-p-radius-xl", layer: "primitive", description: "22px — frame/phone radius." },
  { name: "kw-p-radius-pill", layer: "primitive", description: "999px — pill shape." },
  { name: "kw-p-border-width-hairline", layer: "primitive", description: "1px." },
  { name: "kw-p-border-width-thick", layer: "primitive", description: "2px." },
  { name: "kw-p-border-width-focus", layer: "primitive", description: "3px focus ring width." },
  { name: "kw-p-shadow-light-sm", layer: "primitive", description: "Kept Light phone-frame elevation." },
  { name: "kw-p-shadow-light-md", layer: "primitive", description: "Kept Light desk-panel elevation." },
  { name: "kw-p-shadow-dark-sm", layer: "primitive", description: "Hy3 elevation." },
  { name: "kw-p-shadow-none", layer: "primitive", description: "No elevation." },
  { name: "kw-p-duration-instant", layer: "primitive", description: "120ms." },
  { name: "kw-p-duration-quick", layer: "primitive", description: "200ms." },
  { name: "kw-p-duration-moderate", layer: "primitive", description: "400ms — standard transitions." },
  { name: "kw-p-duration-breathe", layer: "primitive", description: "7000ms — Hy3 ember-thread breathe/pulse." },
  { name: "kw-p-duration-drift", layer: "primitive", description: "9000ms — Kept Light presence-pool drift." },
  { name: "kw-p-easing-standard", layer: "primitive", description: "ease-in-out." },
  { name: "kw-p-easing-linear", layer: "primitive", description: "linear." },
  { name: "kw-p-opacity-full", layer: "primitive", description: "1." },
  { name: "kw-p-opacity-disabled", layer: "primitive", description: "0.5 — disabled controls." },
  { name: "kw-p-opacity-scrim", layer: "primitive", description: "0.7 — scrim overlays." },
  { name: "kw-p-size-viewport-min", layer: "primitive", description: "320px minimum supported viewport width." },
  { name: "kw-p-size-shell-base", layer: "primitive", description: "1180px default shell max-width." },
  { name: "kw-p-size-shell-tablet", layer: "primitive", description: "1120px tablet shell max-width." },
  { name: "kw-p-size-shell-shared", layer: "primitive", description: "1600px shared-surface shell max-width." },
  { name: "kw-p-size-shell-wide", layer: "primitive", description: "1440px wide-viewport shell max-width." },
  { name: "kw-p-size-setup-shell", layer: "primitive", description: "680px setup-form shell max-width." },
  { name: "kw-p-size-card-min-height", layer: "primitive", description: "190px default card min-height." },
  { name: "kw-p-size-card-min-height-room", layer: "primitive", description: "250px room-scale card min-height." },
  { name: "kw-p-size-label-column", layer: "primitive", description: "72px minimum label column width (e.g. schedule times)." },
  { name: "kw-p-size-approval-label-column", layer: "primitive", description: "90px minimum label column width (approval dl terms)." },
  { name: "kw-p-font-size-display-clamp-min", layer: "primitive", description: "2rem clamp() floor for the personal display heading." },
  { name: "kw-p-font-size-display-clamp-min-shared", layer: "primitive", description: "3rem clamp() floor for the shared-surface display heading." },
  { name: "kw-p-font-size-headline-clamp-min", layer: "primitive", description: "1.3rem clamp() floor for the Now-card headline." },
];

const semanticTokens: readonly TokenDescriptor[] = [
  { name: "kw-color-canvas", layer: "semantic", description: "Page background." },
  { name: "kw-color-canvas-raised", layer: "semantic", description: "Card/panel background." },
  { name: "kw-color-canvas-sunken", layer: "semantic", description: "Recessed panel background (e.g. a notes rail)." },
  { name: "kw-color-text-primary", layer: "semantic", description: "Primary text." },
  { name: "kw-color-text-secondary", layer: "semantic", description: "Secondary/muted text." },
  { name: "kw-color-text-faint", layer: "semantic", description: "Faint/placeholder text." },
  { name: "kw-color-border-hairline", layer: "semantic", description: "Default hairline border." },
  { name: "kw-color-border-focus", layer: "semantic", description: "Focus ring color." },
  { name: "kw-color-accent-primary", layer: "semantic", description: "Sparse primary accent (Now items, primary actions)." },
  { name: "kw-color-accent-primary-muted", layer: "semantic", description: "Muted accent background." },
  { name: "kw-color-accent-secondary", layer: "semantic", description: "Calm/secondary accent — always paired with an icon/label." },
  { name: "kw-color-state-calm", layer: "semantic", description: "Calm/available state color, non-color-redundant." },
  { name: "kw-color-state-attention", layer: "semantic", description: "Attention/degraded state color, non-color-redundant." },
  { name: "kw-color-privacy-cue-bg", layer: "semantic", description: "Privacy/session cue background." },
  { name: "kw-color-privacy-cue-text", layer: "semantic", description: "Privacy/session cue text." },
  { name: "kw-color-presence-glow", layer: "semantic", description: "Presence-motif glow color." },
  { name: "kw-color-presence-glow-hi", layer: "semantic", description: "Presence-motif glow highlight color." },
  { name: "kw-color-canvas-glow", layer: "semantic", description: "Faint ambient body-background glow tint (transparent on personal surfaces)." },
  { name: "kw-font-display", layer: "semantic", description: "Greeting/display typeface." },
  { name: "kw-font-body", layer: "semantic", description: "Body typeface." },
  { name: "kw-font-label", layer: "semantic", description: "Eyebrow/label typeface." },
  { name: "kw-letter-spacing-label", layer: "semantic", description: "Label tracking." },
  { name: "kw-shadow-frame", layer: "semantic", description: "Elevation for a device/frame container." },
  { name: "kw-shadow-panel", layer: "semantic", description: "Elevation for an in-page panel." },
  { name: "kw-motion-duration-presence", layer: "semantic", description: "Presence-motif animation duration." },
  { name: "kw-font-size-eyebrow", layer: "semantic", description: "Eyebrow text size." },
  { name: "kw-font-size-label", layer: "semantic", description: "Label text size." },
  { name: "kw-font-size-body", layer: "semantic", description: "Body text size (surface-adjustable)." },
  { name: "kw-font-size-subheading", layer: "semantic", description: "Subheading text size (surface-adjustable)." },
  { name: "kw-font-size-heading", layer: "semantic", description: "Heading text size (surface-adjustable)." },
  { name: "kw-font-size-display", layer: "semantic", description: "Display/greeting text size (surface-adjustable)." },
  { name: "kw-line-height-tight", layer: "semantic", description: "Heading line-height." },
  { name: "kw-line-height-body", layer: "semantic", description: "Body line-height." },
  { name: "kw-space-inline-xs", layer: "semantic", description: "Smallest inline gap." },
  { name: "kw-space-inline-sm", layer: "semantic", description: "Small inline gap." },
  { name: "kw-space-stack-sm", layer: "semantic", description: "Small vertical stack gap." },
  { name: "kw-space-stack-md", layer: "semantic", description: "Medium vertical stack gap." },
  { name: "kw-space-card-padding", layer: "semantic", description: "Card internal padding (surface-adjustable)." },
  { name: "kw-space-section-gap", layer: "semantic", description: "Gap between major sections (surface-adjustable)." },
  { name: "kw-space-page-margin", layer: "semantic", description: "Page-level margin." },
  { name: "kw-radius-input", layer: "semantic", description: "Input/control corner radius." },
  { name: "kw-radius-card", layer: "semantic", description: "Card corner radius." },
  { name: "kw-radius-frame", layer: "semantic", description: "Device/frame corner radius." },
  { name: "kw-radius-pill", layer: "semantic", description: "Pill corner radius." },
  { name: "kw-border-width-hairline", layer: "semantic", description: "Hairline border width." },
  { name: "kw-border-width-thick", layer: "semantic", description: "Thick emphasis border width." },
  { name: "kw-border-width-focus", layer: "semantic", description: "Focus ring width." },
  { name: "kw-focus-offset", layer: "semantic", description: "Focus ring offset from the element edge." },
  { name: "kw-letter-spacing-tight-label", layer: "semantic", description: "Tightly-tracked label letter-spacing (e.g. the mock-data badge)." },
  { name: "kw-size-viewport-min", layer: "semantic", description: "Minimum supported viewport width." },
  { name: "kw-size-shell", layer: "semantic", description: "Default shell max-width." },
  { name: "kw-size-shell-tablet", layer: "semantic", description: "Tablet shell max-width." },
  { name: "kw-size-shell-shared", layer: "semantic", description: "Shared-surface shell max-width." },
  { name: "kw-size-shell-wide", layer: "semantic", description: "Wide-viewport shell max-width." },
  { name: "kw-size-setup-shell", layer: "semantic", description: "Setup-form shell max-width." },
  { name: "kw-size-card-min-height", layer: "semantic", description: "Default card min-height." },
  { name: "kw-size-card-min-height-room", layer: "semantic", description: "Room-scale card min-height." },
  { name: "kw-size-label-column", layer: "semantic", description: "Minimum label column width." },
  { name: "kw-size-approval-label-column", layer: "semantic", description: "Minimum approval-detail label column width." },
  { name: "kw-font-size-display-clamp-min", layer: "semantic", description: "clamp() floor for the personal display heading." },
  { name: "kw-font-size-display-clamp-min-shared", layer: "semantic", description: "clamp() floor for the shared-surface display heading." },
  { name: "kw-font-size-headline-clamp-min", layer: "semantic", description: "clamp() floor for the Now-card headline." },
  { name: "kw-motion-duration-transition", layer: "semantic", description: "Standard UI transition duration." },
  { name: "kw-motion-easing-standard", layer: "semantic", description: "Standard easing curve." },
  { name: "kw-opacity-disabled", layer: "semantic", description: "Disabled-control opacity." },
  { name: "kw-target-min", layer: "semantic", description: "Minimum interactive target size (surface-adjustable)." },
];

const componentTokens: readonly TokenDescriptor[] = [
  { name: "kw-c-presence-blob-radius", layer: "component", description: "Kept Light presence 'light pool' organic border-radius shape." },
  { name: "kw-c-presence-size", layer: "component", description: "Presence-motif bounding box size." },
  { name: "kw-c-presence-size-large", layer: "component", description: "Presence-motif bounding box size at room scale." },
  { name: "kw-c-presence-line-height", layer: "component", description: "Hy3 presence 'quiet line' thickness." },
  { name: "kw-c-presence-dot-size", layer: "component", description: "Hy3 presence traveling-dot size." },
  { name: "kw-c-card-frame-radius", layer: "component", description: "Card frame corner radius (aliases radius-frame)." },
  { name: "kw-c-card-frame-shadow", layer: "component", description: "Card frame elevation (aliases shadow-frame)." },
  { name: "kw-c-composer-radius", layer: "component", description: "Assistant-input composer corner radius." },
];

export const tokens: readonly TokenDescriptor[] = [...primitiveTokens, ...semanticTokens, ...componentTokens];

export const tokenNames: ReadonlySet<string> = new Set(tokens.map((token) => token.name));

export function tokenLayer(name: string): TokenLayer | undefined {
  return tokens.find((token) => token.name === name)?.layer;
}
